"""Initial tables

Revision ID: 1ac3527e284a
Revises: 
Create Date: 2025-05-25 02:00:12.876748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac3527e284a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'inventory',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_products_product_id', table_name='products')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_users_user_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_products_product_id', 'products', ['product_id'], unique=False)
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'inventory',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
