"""Add cart and order tables

Revision ID: 42935d289438
Revises: 1ac3527e284a
Create Date: 2025-05-25 02:32:41.430804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42935d289438'
down_revision: Union[str, None] = '1ac3527e284a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['user_id'])
    op.alter_column('orders', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
